---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "ci(deps): "
    schedule:
      interval: weekly
      day: friday
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: "chore(deps): "
    schedule:
      interval: weekly
      day: friday
      time: "00:00"
      timezone: UTC
    open-pull-requests-limit: 10
